### ISSUE TITLE
Evidence of CRAN struggling to scale?

### ISSUE THREAD

**Issue by llrs** [cranchange/cran_change.org#23]
On the new draft there is this central sentence:

> Unfortunately, we, the undersigned R community members, are unified in our concern that CRAN is showing signs that it is struggling to scale with the popularity of the R language.

Is there any evidence of this? How is this identified if CRAN is not scaling well enough? More rejected packages? Longer reviews? More negative feedback from package authors? More packages being archived? 

I haven't seen any increase of rejections or longer reviews on the last 9 months. But perhaps it refers to package archived.

**Comment by MilesMcBain** [comment]
I think signs are:

* tightening policy and criteria, including undocumented criteria.
* increasing(?) use of short archival timeframes
* Archival without warning
* Archival immediately after acceptance as noted by https://rviews.rstudio.com/2021/04/22/march-2021-top-40-new-cran-packages/

Statistics around those would be useful but they're hard if not impossible to get.

**Comment by adamhsparks** [comment]
While I agree with the sentiment and probably have been at least partially responsible for it as I do feel that this may be an issue, I'm not sure I'd put it in writing, since we have no real data on the matter. It's just a gut feeling based on our observations as to what may be happening. I think that we need to stick to what we know to be true and offer courses of remediation that benefit both CRAN volunteers and developers.

**Comment by MilesMcBain** [comment]
This sentence is important because it states the motivation for the petition. 

If it speaks truly to our intuition about the source of the problem, but involves events we can't possibly have data about, then support for the petition becomes the data that validates the concern.

I agree it's not ideal, but part of the problem we are facing is lack of transparency.

I'm happy to consider alternatives.

**Comment by MilesMcBain** [comment]
I originally had a sentence about "inconsistency" and I still like that frame, but any negative words about CRAN seemed to be triggering for some people.

**Comment by MilesMcBain** [comment]
What about

> ... CRAN is showing signs that it is struggling to deal with contributors in a consistent manner.

I don't mind it, but does it capture the extent of the issues?

**Comment by MilesMcBain** [comment]
Or just 

> struggling to deal with contributors consistently.

**Comment by adamhsparks** [comment]
Your last option sums up what we've seen and is clearly demonstrable IMO.

**Comment by MilesMcBain** [comment]
Cool although I also like:

> Struggling to create a consistent experience for contributors.

Since it is broader.

**Comment by adamhsparks** [comment]
that's fine with me as well

**Comment by llrs** [comment]
I like much more either of the last two options than the current sentence. 

Data about package removed could be obtained using CRANberries database of [package removals](https://dirk.eddelbuettel.com/cranberries/cran/removed/) and related to the acceptance dates using [pkgsearch](https://cran.r-project.org/web/packages/pkgsearch/index.html).

**Comment by MilesMcBain** [comment]
I think analysis like that could be interesting, but also we could spend a lot of time on it and turn up nothing conclusive.

Would we find a necessarily find change point in archival rates, or has there been a steady slide? And over what period are we looking? I think this has probably been going on for a long while, it's just taken some time for enough stories to be swapped to build community awareness.

Archival itself is not the issue, it is more about the circumstances around it. What was the reason? How long a timeframe was given? How was the resubmission process etc? I don't think we'll find a better data source for this than `cran_histories`.

**Comment by MilesMcBain** [comment]
Likewise with submissions etc. I don't know if we see resubmission attempts etc over a long enough time?

**Comment by MilesMcBain** [comment]
I changed the sentence in the draft.
